CREATE TABLE BE (
SELECTED_STUDENTS VARCHAR,
PLACED_STUDENT VARCHAR,
PLACED BOOLEAN ,
COMPANY_NAME VARCHAR,
COMPANY_ID BIGINT
)
select * from BE
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED,COMPANY_NAME,COMPANY_ID)VALUES
('AA','AA',TRUE,'HCL',1212)
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED,COMPANY_NAME,COMPANY_ID)VALUES
('pp','null',TRUE,'HCL',1212),
('BB','AA',TRUE,'HCL',4344),
('BFG','AA',TRUE,'ACCENTURE',344),
('AAFRF','AA',TRUE,'HCL',43455),
('AATGTG','AA',TRUE,'TCS',198867),
('AAFRERR','AA',TRUE,'HEXA',56534)

INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED,COMPANY_NAME,COMPANY_ID)VALUES
('erpp','null',TRUE,'HCL',1212),
('rgBB','rter',TRUE,'HCL',4344),
('qwBFG','AAwe',TRUE,'ACCENTURE',344),
('xxAAFRF','DFAA',TRUE,'HCL',43455),
('zzAATGTG','WEAA',TRUE,'TCS',198867),
('uiAAFRERR','QWAA',TRUE,'HEXA',56534)
SELECT *FROM BE
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED,COMPANY_NAME,COMPANY_ID)VALUES
('TRerpp','null',TRUE,'HCL',1212),
('UYrgBB','rter',TRUE,'HCL',4344),
('qwBFG','AAwe',TRUE,'ACCENTURE',344),
('xxAAFRF','DFAA',TRUE,'HCL',43455),
('zzAATGTG','WEAA',TRUE,'TCS',198867),
('uiAAFRERR','QWAA',TRUE,'HEXA',56534),
('WWWpp','null',TRUE,'HCL',1212),
('WWWBB','AA',TRUE,'HCL',4344),
('IIBFG','AA',TRUE,'ACCENTURE',344),
('AAFRF','AA',TRUE,'HCL',43455),
('AATGTG','AA',TRUE,'TCS',198867),
('AAFRERR','AA',TRUE,'HEXA',56534)
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED)VALUES
('TRerpp','null',TRUE),
('SUJAL','SUJAL',TRUE),
('SHRUTI','SHRUTI',TRUE),
('TRerpp','null',TRUE),
('FTERTG','SUJAL',TRUE),
('RREFTR','SHHAU',TRUE),
('HGYTHGYTHYG','SHRUTI',TRUE)
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED)VALUES
('TRerpp','null',TRUE),
('SUJAL','SUJAL',TRUE),
('SHRUTI','SHRUTI',TRUE),
('TRerpp','null',TRUE),
('FTERTG','SUJAL',TRUE),
('RREFTR','SHHAU',TRUE),
('HGYTHGYTHYG','SHRUTI',TRUE)
SELECT * FROM BE
INSERT into BE(PLACED)VALUES
('SUJAL')
INSERT into BE(SELECTED_STUDENTS,PLACED_STUDENT,PLACED)VALUES
('TRerpp','null',TRUE),
('SUJAL','SUJAL',TRUE),
('SHRUTI','SHRUTI',TRUE),
('TRerpp','null',TRUE),
('FTERTG','SUJAL',TRUE),
('RREFTR','SHHAU',TRUE),
('HGYTHGYTHYG','SHRUTI',TRUE)
SELECT * FROM BE