CREATE TABLE LIBRARY (
    BOOK_ID BIGINT PRIMARY KEY,
    BOOK_TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    GENRE VARCHAR(100),
    PUBLICATION_YEAR INT
);
INSERT INTO LIBRARY (BOOK_ID, BOOK_TITLE, AUTHOR, GENRE, PUBLICATION_YEAR) VALUES
(1, 'To Kill a Mockingbird', 'Harper Lee', 'Fiction', 1960),
(2, '1984', 'George Orwell', 'Dystopian', 1949),
(3, 'Pride and Prejudice', 'Jane Austen', 'Romance', 1813),
(4, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', 1925),
(5, 'Moby-Dick', 'Herman Melville', 'Adventure', 1851),
(6, 'War and Peace', 'Leo Tolstoy', 'Historical', 1869),
(7, 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 1951),
(8, 'Crime and Punishment', 'Fyodor Dostoevsky', 'Psychological Fiction', 1866),
(9, 'Brave New World', 'Aldous Huxley', 'Dystopian', 1932),
(10, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 1937),
(11, 'Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 1953),
(12, 'Jane Eyre', 'Charlotte Brontë', 'Romance', 1847),
(13, 'Wuthering Heights', 'Emily Brontë', 'Gothic', 1847),
(14, 'The Odyssey', 'Homer', 'Epic', NULL),
(15, 'The Divine Comedy', 'Dante Alighieri', 'Epic', 1320),
(16, 'Les Misérables', 'Victor Hugo', 'Historical', 1862),
(17, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical Fiction', 1880),
(18, 'A Tale of Two Cities', 'Charles Dickens', 'Historical', 1859),
(19, 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 1954),
(20, 'Dracula', 'Bram Stoker', 'Horror', 1897),
(21, 'The Picture of Dorian Gray', 'Oscar Wilde', 'Gothic', 1890),
(22, 'Frankenstein', 'Mary Shelley', 'Science Fiction', 1818),
(23, 'Anna Karenina', 'Leo Tolstoy', 'Romance', 1877),
(24, 'Don Quixote', 'Miguel de Cervantes', 'Adventure', 1605),
(25, 'The Iliad', 'Homer', 'Epic', NULL),
(26, 'Great Expectations', 'Charles Dickens', 'Classic', 1861),
(27, 'The Count of Monte Cristo', 'Alexandre Dumas', 'Adventure', 1844),
(28, 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 1967),
(29, 'The Sound and the Fury', 'William Faulkner', 'Modernist', 1929),
(30, 'Ulysses', 'James Joyce', 'Modernist', 1922),
(31, 'The Metamorphosis', 'Franz Kafka', 'Absurdist Fiction', 1915),
(32, 'Beloved', 'Toni Morrison', 'Historical', 1987),
(33, 'Madame Bovary', 'Gustave Flaubert', 'Realism', 1856),
(34, 'The Old Man and the Sea', 'Ernest Hemingway', 'Adventure', 1952),
(35, 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Science Fiction', 1969),
(36, 'The Stranger', 'Albert Camus', 'Philosophical Fiction', 1942),
(37, 'Heart of Darkness', 'Joseph Conrad', 'Colonial Literature', 1899),
(38, 'Lolita', 'Vladimir Nabokov', 'Psychological Fiction', 1955),
(39, 'The Sun Also Rises', 'Ernest Hemingway', 'Modernist', 1926),
(40, 'Catch-22', 'Joseph Heller', 'Satire', 1961);
SELECT * FROM LIBRARY